language: scala

# scala versions to test against
scala:
 - 2.12.1
 - 2.11.8

jdk:
 - oraclejdk8


script:
  - sbt clean compile "testOnly fs2.interop.reactive.UnicastPublisherSpec"

after_success:
- bash <(curl -s https://codecov.io/bash)