language: scala
scala:
- 2.11.8
- 2.12.1
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi
script:
- |
  if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ "$TRAVIS_BRANCH" = "master" ] && [[ $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
    openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in secrets.tar.enc -out secrets.tar -d
    tar xvf secrets.tar
    sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport publishSigned
  else
    sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport
  fi
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- bash <(curl -s https://codecov.io/bash)
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION"
env:
  global:
  - secure: j3irJXaXvubg3C+6vziEy0jYnV0kLAV7oGayl30kZZa8WvicVQSXhRAcRBEmBMO2AvYRAkMxgIdmF3eQWLHCdY/G7pIPqMrWyz9Y7W7UOULhjsZgboncdHxkoIPxlMuWZBhx8KIuf8AqJOyQneYsZcrG5+ikb7xus1Nln9TIM01UCTxPIqAav+w1Ihuj0BiAHqzNwtNuQ1FIzcqJD0mrsnEpzpKHF/3UuLzMWfP1L+xaKkW247BzhYegnmCqRFH5gOhZdJ/4Hgh0oZwt2WpBUTGqfJeLybjYrDvT3Dt1SUpUvEIC6F40a1FhcjRi3arymg5gTJcb6vVOGj8JdfPJYhgC65wvVxr4fyq+poPnMLDh6KkH/xXLWGy+g7JPSQN2fmAtSCFzaxtaEEwi29OQuYmGPeAIdNd1ZTnOP1Zo+BRtnWX7U8if9XdjOzHdhhigjxsQCOhAWJI7Rf2m7QzmU+64j6Ck2yrFuBLpluJHBVQgWQyKAkU4+YIYDoGxcVfUeUf9CjIBDPZ2/CtqUd5BRWfBaCXQ1MZ38ByGvLI2YWB0E7DQmHlsZbiOgox2zlgfaNR4LK1IWJAyuL6ik87OZPdA4SglvU5fONTw1B9tSIc10AqyR7Iu7op2Ph1oZUc9tCkLmOjJnI3GOKE25zeXpbf1idRQYWlRZUXbG0i63XY=
  - secure: jjnnfAou2n27cEYnNhn+txr+e1vwo9UetV7VIfxBQ6Didoqg08iXMQpgSdlKvlgoSFTEA8vZKxpXxv/GDk2+WwxGNpDq/HVvru7rE1mylO6IlzvPRZ/NS12e/sgFOpE7Js/dAxbKwP0WXDFvCPOzbYTOT04hy8jTx72fnHM37zMKWZ+kiLXAwSTBV2fVOoBBnWNE9UMWm6EMtmRxFFHdFzKmp1ZV8J8JpZvV8wz6im+/VG115a9f4Cya311uPPBfpsZizt9vY7pM9oABIGfT1kQhZQ+OTomltUQ9tgtvcbKMBji5tSUB/QG/pWhXGLNpcogF/BMay6rsD6Zf489KICaFrCPXpPebAir8sYxq/+Z6vD8rv8dm/A7WyiPeJ5GK6VXifmyAOks+U0EzR03Y2G3zV6a2Yqs5udl4w3NUicaxA4jLNkhT8AAZnl9ITLBYsh1CaTdHo1DTqCQtsKeKBwhuxjHHYH3zknjnVduLjI2FttkgKExflq0SCY2/Dk8w7XFmwIxgMpYmuOsWcv1o9VCLleuVQbnOCPlqAvVCkubhLrgLDkqg7iRkwA71BULqfyIcjG9S/kW9z8DqPupCuTN+Xc13RJKzsfAtsKksTiWcaB8DiphgDwU1hV1ZRxuW5axghzLfCzvdlCrHMRWJdicHoyjtUnvknw478Vu+lUs=
  - secure: mLQG5ocfu4nmAgpFcxVT8NIJTcEXbauWfLVZoWKRhvvcZ6PPAM/8eci6YiEWIP3toHK63fvB63IjEKWATRrrzrWxhy+i6e06CLDX8oxh4LUPW6MAsqP4RIRLNYduI+70ERmE7SDZjizMOjD31gkYd7/Xp+dF9DDCs3tjPXkACpGxNhMrZs+Q5ESRAFRMQikzsuQVHJkPnyEyyEGvhDFVEtxIYS1NhCUieNWVr+/2F37HEFjxIPDzakkLrfOzmGiFZ7u8PSdSK+AnK64jFfE3iSBK3bAt2mQvx+X0bOZGzRpFY2rZzal1qkj+LEnMx2g7vwxxDcTH6huK8Og64+6ofMp/IeY/8n8jm09ykBj4ic6N9kWWhcfzvfxoye1hPMZ4cs7f7W74Arfi+1NsW1p7bK6x3EcWvlnoiZ2vdG1RxtMZPGFLDpQTkRyC4/W/7p1pHm/piiZjIqko5mEBv4kLC+eh8qfd1d9iromNNGsn3TQex3+rqRQbPLS/ndniOfvr217bdtwtrEqBEPV8UcCfaz9AX3/gD3sR5NMei/lOUGovXd6/406eDXAK0M2sKKzk5yU3WtSCTWi1HbtriP8jO4tcbYp3oeFn6SPr8NqnVS5blAJlGK5TLF76dxs1p5LYmzGm+6WpakGdY/3hTrzi3NlgWEcZga8QumKvH9Zoqvg=
